// Code generated by update-protocol-version.ts. DO NOT EDIT.

/// SDK protocol version
/// This must match the version expected by the copilot-agent-runtime server
pub const SDK_PROTOCOL_VERSION: i32 = 1;

/// Get the SDK protocol version
pub fn get_sdk_protocol_version() -> i32 {
    SDK_PROTOCOL_VERSION
}
